overlay.d/05core: disable bootloader-update.service on live ISO
When running from live-iso `bootupctl` fails with:

    error: Querying adoptable state: creation time is not available for the filesystem

That happens because filesystem (erofs|squashfs) doesn't support statx.stc_btime field:

    $ stat /sysroot/.coreos-aleph-version.json
    Access: 2022-08-01 23:42:11.000000000 +0000
    Modify: 2022-08-01 23:42:11.000000000 +0000
    Change: 2022-08-01 23:42:11.000000000 +0000
     Birth: -