Revert "coreos-teardown-initramfs: use NetworkManager to teardown networking"
This reverts commit b8607dabb5e1a5a0795fe11b5089889038c150f6.

We're seeing around 75% failure rate with this patch when provisioning
RHCOS on AWS with m4 instance types. The error message is:

    Error: failed to set networking: Timeout was reached

I confirmed that D-Bus and NM are definitely still running when we issue
the `nmcli` call. Still, I think there's a subtle race somewhere (likely
combined with the specific network adapter of m4 instance types), that
we need to plug. We need more visibility into why NM isn't responding.
Anyway, for now let's revert this to not regress.

Fixes: https://issues.redhat.com/browse/OCPBUGS-17154
Probably fixes: https://issues.redhat.com/browse/OCPBUGS-19870