ci/overrides: fix Bodhi lookup with bodhi-client 6.x
We were assuming that bodhi.client re-exported bodhi.client.bindings, but
apparently that wasn't contractual.  Import the module we actually need.

Fixes error:

    AttributeError: module 'bodhi.client' has no attribute 'bindings'