overrides: drop systemd-253.4-1.fc39 pin
We need to drop this pin to resolve dependency problems in the current
rawhide package set. Here is a snippet of the failure we're seeing now:

---
error: Could not depsolve transaction; 4 problems detected:
 Problem 1: package rpm-libs-4.18.91-6.fc39.x86_64 from fedora-rawhide requires rpm = 4.18.91-6.fc39, but none of the providers can be installed
  - package rpm-4.18.91-6.fc39.x86_64 from fedora-rawhide conflicts with systemd < 253.5-6 provided by systemd-253.4-1.fc39.x86_64 from fedora-coreos-pool
  - package rpm-ostree-2023.5-1.fc39.x86_64 from fedora-rawhide requires librpm.so.10()(64bit), but none of the providers can be installed
  - package rpm-ostree-2023.5-1.fc39.x86_64 from fedora-rawhide requires librpmio.so.10()(64bit), but none of the providers can be installed
  - conflicting requests
---

i.e. the newer rpm needs a newer `systemd` than the one we had
pinned for https://github.com/coreos/fedora-coreos-tracker/issues/1508

For rawhide we can unpin and just denylist the tests https://github.com/coreos/fedora-coreos-config/pull/2492.