tests/validate-symlinks: add exception for libmtcr_ul.a
Recently mstflint.rpm was added for el9 and el10, so this test
now fails on broken /usr/lib64/libmtcr_ul.a:
```
Error: /usr/lib64/libmtcr_ul.a symlink to /usr/lib64/mstflint/libmtcr_ul.a which does not exist
```